Added github repo links and sample project on main page
AI-ON/ai-on.org pull request #6
Opened 2016-10-23 18:10 UTC by 0bserver07

In reply to issue #5 

There seems to be only 1 project so far with a public repository, or I couldn't find them with the Project title given on Projects page.

Later to be added.

2016-10-25 16:53 UTC, fchollet requested changes
Please do not check anything into `website/`, that content is autogenerated. Added content should go in `templates/`, `'build.py`, etc.

2016-10-25 16:53 UTC, fchollet commented on build.py
> +    headers = {'title', 'date', 'category', 'contact', 'tagline', 'mailing_list','repository'}
Space after comma

2016-10-26 04:59 UTC, 0bserver07 commented
1. fixed the /website (my bad first time using this py static site, usually Jekyll).
2. added the ai-on-example repo link.
3. added social-bot- repo link (people to find it)
4. added Gitter to main page and readme (I wasn't quite sure about the way I linked them though)

2016-10-26 17:08 UTC, fchollet requested changes
Mention of the example project and the Gitter channel should go in /process. The landing page is for high-level info. Thanks!

2016-10-26 20:34 UTC, 0bserver07 commented
All good now, wasn't sure if I should remove the gitter from readme.md or not though. (I thought it might help people when they find it on Github)

2016-10-26 20:58 UTC, fchollet commented
LGTM, thanks!

2016-10-26 20:58 UTC, merged